{% set name = "microsoft-kiota-serialization-json" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_json-{{ version }}.tar.gz
  sha256: 9f6ac6591ac219c31884b13e7619e424ae2a4772e30c886ea3a853f998efde5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - pendulum >=2.1.2

test:
  imports:
    - kiota_serialization_json
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/json
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - xylar
