{% set name = "microsoft-kiota-serialization-json" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_json-{{ version }}.tar.gz
  sha256: 46370cb3563b8167829142ab7b745b28cbf743d367ffc6a25995b5d832537b1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - microsoft-kiota-abstractions
    - pendulum >=3.0.0b1

test:
  imports:
    - kiota_serialization_json
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/json
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - xylar
